bool_type_columns:
- RainToday
- RainTomorrow
columns_groupby:
- Location
- Year
- Month
csv: results/data.csv
date_column: Date
draft_csv: weatherAus.csv
insert_Rainfall:
- 1
- 0
insert_day:
- 0
- 1
knn:
  weights:
  - uniform
  - distance
  metric:
  - euclidean
  - manhattan
  - haversine
  - minkovski
  n_neighbors:
  - 5
  - 7
  - 8
  - 10
korelation_limit:
- 0.87
- 0.73
- 0.68
- 0.66
log_reg:
  C:
  - 0.25
  - 0.5
  - 0.75
  - 1.0
  max_iter:
  - 300
  - 500
  - 800
missing_cat: mode
null_limit:
- 0.38
- 0.4
- 0.43
- 0.47
random_forest:
  n_estimators:
  - 100
  - 150
  - 200
  criterion:
  - gini
  - entropy  
tail_len:
- 1.5
- 1.75
- 2
- 2.25
- 2.5
target: RainTomorrow
test_size: 0.3